package managementFiles.Database;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class BookDAO {
    
    private String URL;

    private Connection getConnection() throws Exception {
        DatabaseConnection connection = new DatabaseConnection(URL);
        return connection.getConnection(); 
    }
    
    // Cleaned up the constructor: DAOs only need the DB path, not a stateful Book field!
    public BookDAO(String url) {
        this.URL = url;
    }

    // ==========================================
    // 1. CREATE (Inserting into 3 Tables)
    // ==========================================
    public void add(Book book) throws Exception {
        String insertBookSql = "INSERT INTO books (title, isbn) VALUES (?, ?)";
        String insertAuthorSql = "INSERT INTO book_authors (book_id, author_name) VALUES (?, ?)";
        String insertCopySql = "INSERT INTO book_copies (book_id, barcode, isAvailable) VALUES (?, ?, ?)";

        try (Connection conn = getConnection()) {
            // Disable auto-commit to run this safely as a single ACID Transaction
            conn.setAutoCommit(false);

            try (PreparedStatement pstmtBook = conn.prepareStatement(insertBookSql, PreparedStatement.RETURN_GENERATED_KEYS)) {
                pstmtBook.setString(1, book.getTitle());
                pstmtBook.setString(2, book.getIsbn());
                pstmtBook.executeUpdate();

                // Snatch the autogenerated ID SQLite just made for this book
                ResultSet generatedKeys = pstmtBook.getGeneratedKeys();
                if (generatedKeys.next()) {
                    int generatedBookId = generatedKeys.getInt(1);

                    // Insert associated authors
                    try (PreparedStatement pstmtAuthor = conn.prepareStatement(insertAuthorSql)) {
                        for (BookAuthor author : book.getAuthors()) {
                            pstmtAuthor.setInt(1, generatedBookId);
                            pstmtAuthor.setString(2, author.getAuthorName());
                            pstmtAuthor.addBatch();
                        }
                        pstmtAuthor.executeBatch();
                    }

                    // Insert associated physical copies
                    try (PreparedStatement pstmtCopy = conn.prepareStatement(insertCopySql)) {
                        for (BookCopy copy : book.getCopies()) {
                            pstmtCopy.setInt(1, generatedBookId);
                            pstmtCopy.setString(2, copy.getBarcode());
                            pstmtCopy.setInt(3, copy.isAvailable() ? 1 : 0);
                            pstmtCopy.addBatch();
                        }
                        pstmtCopy.executeBatch();
                    }
                }
                conn.commit(); // Save all changes together
                System.out.println("Book and all its relational graph leaves inserted successfully!");
            } catch (Exception e) {
                conn.rollback(); // Undo everything if a single point fails
                throw e;
            }
        }
    }

    // ==========================================
    // 2. READ BY ID (Fetches Graph Structure & Outputs JSON String)
    // ==========================================
    public String readByID(int id) {
        try (Connection conn = getConnection()) {
            Book book = fetchBookGraph(conn, "SELECT * FROM books WHERE id = ?", String.valueOf(id));
            if (book == null) return null;
            return convertBookToJSON(book);
        } catch (Exception e) {
            return "{\"error\": \"Database error: " + e.getMessage() + "\"}";
        }
    }

    // ==========================================
    // 2b. READ BY NAME (Same logic, different query column)
    // ==========================================
    public String readByName(String name) {
        try (Connection conn = getConnection()) {
            // Using LIKE allows for flexible pattern matching
            Book book = fetchBookGraph(conn, "SELECT * FROM books WHERE title LIKE ?", "%" + name + "%");
            if (book == null) return null;
            return convertBookToJSON(book);
        } catch (Exception e) {
            return "{\"error\": \"Database error: " + e.getMessage() + "\"}";
        }
    }

    // ==========================================
    // 3. UPDATE (Updating availability status of a physical item)
    // ==========================================
    public boolean updateCopyAvailability(String barcode, boolean isAvailable) throws Exception {
        String sql = "UPDATE book_copies SET isAvailable = ? WHERE barcode = ?";
        try (Connection conn = getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setInt(1, isAvailable ? 1 : 0);
            pstmt.setString(2, barcode);
            int rows = pstmt.executeUpdate();
            
            if(rows==0) {return false;}
            else {
           
            System.out.println("Copy availability updated. Rows affected: " + rows);
         // Add this right under your println("Rows affected: " + rows);
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery("SELECT isAvailable FROM book_copies WHERE barcode = '" + barcode + "'")) {
                if (rs.next()) {
                    System.out.println("VERIFICATION: The database file Java is touching actually holds: " + rs.getInt("isAvailable"));
                }
            }
            return true;
            
            }
        }
    }

    // ==========================================
    // 4. DELETE (Relies on Cascade Delete configuration)
    // ==========================================
    public void delete(int id) throws Exception {
        String sql = "DELETE FROM books WHERE id = ?";
        try (Connection conn = getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setInt(1, id);
            int rows = pstmt.executeUpdate();
            System.out.println("Book record deleted from database. Rows wiped: " + rows);
        }
    }

    // ========================================================================
    // HELPER METHODS: Graph Construction and Manual JSON Serialization
    // ========================================================================
    
    private Book fetchBookGraph(Connection conn, String querySql, String queryParam) throws SQLException {
        Book book = null;
        
        try (PreparedStatement pstmt = conn.prepareStatement(querySql)) {
            pstmt.setString(1, queryParam);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    book = new Book();
                    book.setId(rs.getInt("id"));
                    book.setTitle(rs.getString("title"));
                    book.setIsbn(rs.getString("isbn"));
                }
            }
        }

        // If core blueprint is found, query its child nodes
        if (book != null) {
            // Fetch Authors
            String authorSql = "SELECT * FROM book_authors WHERE book_id = ?";
            try (PreparedStatement pstmtAuth = conn.prepareStatement(authorSql)) {
                pstmtAuth.setInt(1, book.getId());
                try (ResultSet rsAuth = pstmtAuth.executeQuery()) {
                    while (rsAuth.next()) {
                        book.addAuthor(new BookAuthor(rsAuth.getInt("id"), rsAuth.getInt("book_id"), rsAuth.getString("author_name")));
                    }
                }
            }
            
            // Fetch Physical Copies
            String copySql = "SELECT * FROM book_copies WHERE book_id = ?";
            try (PreparedStatement pstmtCopy = conn.prepareStatement(copySql)) {
                pstmtCopy.setInt(1, book.getId());
                try (ResultSet rsCopy = pstmtCopy.executeQuery()) {
                    while (rsCopy.next()) {
                        book.addCopy(new BookCopy(rsCopy.getInt("copy_id"), rsCopy.getInt("book_id"), rsCopy.getString("barcode"), rsCopy.getInt("isAvailable") == 1));
                    }
                }
            }
        }
        return book;
    }

    private String convertBookToJSON(Book book) {
        StringBuilder json = new StringBuilder();
        json.append("{");
        json.append("\"id\":").append(book.getId()).append(",");
        json.append("\"title\":\"").append(book.getTitle()).append("\",");
        json.append("\"isbn\":\"").append(book.getIsbn()).append("\",");
        
        // Authors Sub-Array
        json.append("\"authors\":[");
        for (int i = 0; i < book.getAuthors().size(); i++) {
            json.append("\"").append(book.getAuthors().get(i).getAuthorName()).append("\"");
            if (i < book.getAuthors().size() - 1) json.append(",");
        }
        json.append("],");

        // Copies Sub-Array
        json.append("\"copies\":[");
        List<BookCopy> copies = book.getCopies();
        for (int i = 0; i < copies.size(); i++) {
            BookCopy copy = copies.get(i);
            json.append("{");
            json.append("\"copy_id\":").append(copy.getCopyId()).append(",");
            json.append("\"barcode\":\"").append(copy.getBarcode()).append("\",");
            json.append("\"isAvailable\":").append(copy.isAvailable());
            json.append("}");
            if (i < copies.size() - 1) json.append(",");
        }
        json.append("]");
        json.append("}");
        return json.toString();
    }
}